sudo: required

language: node_js

node_js:
  - 4.0
  - 4.1
  - 4.2
  - 4.3
  - 4.4
  - 5.1
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 5.7
  - 5.8
  - 5.9
  - 5.10
  - stable

services:
  - docker

before_script:
  - docker run -d -p 2424:2424 -e "ORIENTDB_ROOT_PASSWORD=root" --name orientdb orientdb/orientdb:2.1.5

after_script:
  - docker stop orientdb
  - docker rm orientdb